name: Continuous Build and Deploy

on:
    push:
        branches:
            - main

jobs:
    build_and_deploy:
        runs-on:
            ubuntu-latest
            
        steps:
            - name: clone
              uses: actions/checkout@v2
            
            - name: build
              run: npm install
                     
            - name: deploy
              uses: amondnet/vercel-action@v20
              with:
                vercel-token: ${{ secrets.VERCEL_TOKEN }}
                vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
                vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}                    
